version: '2'
services:
    justraduire-app:
        image: justraduire
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://justraduire-postgresql:5432/justraduire
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    justraduire-postgresql:
        extends:
            file: postgresql.yml
            service: justraduire-postgresql
